
#Eater Attributes
[eater]
	#Eater health [default: 32]
	#Range: 1.0 ~ 1024.0
	health = 32.0
	#Eater attack damage [default: 15]
	#Range: 0.0 ~ 1024.0
	damage = 15.0
	#Eater armor [default: 5]
	#Range: 0.0 ~ 30.0
	armor = 5.0
	#Eater armor toughness [default: 2]
	#Range: 0.0 ~ 20.0
	armorToughness = 2.0

#Walker Attributes
[walker]
	#Walker health [default: 100]
	#Range: 1.0 ~ 1024.0
	health = 100.0
	#Walker armor [default: 5]
	#Range: 0.0 ~ 30.0
	armor = 5.0
	#Walker armor toughness [default: 4]
	#Range: 0.0 ~ 20.0
	armorToughness = 4.0

#Crusher Attributes
[crusher]
	#Crusher health [default: 16]
	#Range: 1.0 ~ 1024.0
	health = 16.0
	#Crusher attack damage [default: 6]
	#Range: 0.0 ~ 1024.0
	damage = 6.0
	#Crusher armor [default: 20]
	#Range: 0.0 ~ 30.0
	armor = 20.0
	#Crusher armor toughness [default: 4]
	#Range: 0.0 ~ 20.0
	armorToughness = 4.0

#Glider Attributes
[glider]
	#Glider health [default: 14]
	#Range: 1.0 ~ 1024.0
	health = 14.0

#Soarer Attributes
[soarer]
	#Soarer health [default: 20]
	#Range: 1.0 ~ 1024.0
	health = 20.0
	#Soarer attack damage [default: 6]
	#Range: 0.0 ~ 1024.0
	damage = 6.0

